### ISSUE TITLE
After clicking Join, the page will refresh, and the login cannot be successful

### ISSUE THREAD

**Issue by liunaiming** [edumeet/edumeet#918]
I  local install the project on macOS 10.15 locally， beside using coturn， I follow the install guild，Howerer，when I click Join Button， the page refreshed and did not enter the chatroom，could you help me, this trouble me several days，thank you！
![image](https://user-images.githubusercontent.com/53079086/138279811-ec8c2c03-9d89-438c-a0c3-5c98028c2d7a.png)

How can I enter the next step to chat?

**Comment by roman-drozd-it** [comment]
Hi, It's probably some problem/bug related with your browser interface language (chinese?)

1. Provide me an information about your browser's lang by putting the below code to the console and let's us know what;s the result.
`console.log("window.navigator.userLanguage: " + window.navigator.userLanguage + " | window.navigator.language: "+ window.navigator.language)`

2. Provide your envirnonment  setup you use:
- browser name & version, 
- node.js version, 
- package manager name & version, 
- branch name (i guess it's master)

3. Can you try to run edumeet on a system/browser with a native english interface and see if the problem still occurs?

4. Try to run a develop version where this problem may be already solved (AFAIR ther was some problem with "chinese" languages that has been fixed on develop  branch

**Comment by narenltk** [comment]
Hi @roman-drozd-it,

Version used,
Npm Version: 6.14.15
Node Version: 12.22.1
Branch: Master
Browser: Chrome latest version

I am facing the similar issues and here is the details which you requested, this is the latest git clone.
Previously I was using Node version: 10.19.0 and everything was fine.

Now I have been facing this issue, 
When I do npm start at edumeet/server I have been facing some issues so upgraded to V12.22.1.

Have a look at the console . it is nothing more than React and Material UI warning nothing more than that.

![join dialog page](https://user-images.githubusercontent.com/14790887/145770646-1d629946-6e6e-4540-a952-b8965c26c9ca.png)

I have created my own Certificate and where I have changed the Local host as the IP address for the local development.

Will be great if you can suggest some ideas

**Comment by tomhanax** [comment]
I have same problem - reload after login button, but the only interesting message in console is: WebSocket connection to '....' failed: WebSocket is closed before the connection is established. I have configured correct listenIP in webRtcTransport and have good certificates. Any suggestion?

**Comment by liqiuying-hcy** [comment]
I have set up the window.navigator.language to be "en",but the console still show the error in the first picture

**Comment by liqiuying-hcy** [comment]
I have seted up the window.navigator.language to be "en",but the console still show the error .If I click the Join button,the network will show Provisional headers are shown.In the edumeet source code,i have changed the mediasoup version into 2.6.19 because version of 3 i can't successfully npm install,and the redis version change to 4.0.3 so that when I npm start in the server there no error in the terminal.
![image](https://user-images.githubusercontent.com/60089252/154383371-a138a595-6e0e-456e-a463-cb7f925e77b2.png)
![image](https://user-images.githubusercontent.com/60089252/154383405-e4089e01-9fdf-40df-b32f-6d94b6161f65.png)
![image](https://user-images.githubusercontent.com/60089252/154384126-ef3b733e-aeba-4b77-8041-fbf30e158fad.png)
browsername:chrome
node.js version:13.7.0
npm:6.13.6
branch name:master

**Comment by liqiuying-hcy** [comment]
I have seted up the window.navigator.language to be "en",but the console still show the error .If I click the Join button,the network will show Provisional headers are shown.In the edumeet source code,i have changed the mediasoup version into 2.6.19 because version of 3 i can't successfully npm install,and the redis version change to 4.0.3 so that when I npm start in the server there no error in the terminal.
![image](https://user-images.githubusercontent.com/60089252/154383371-a138a595-6e0e-456e-a463-cb7f925e77b2.png)
![image](https://user-images.githubusercontent.com/60089252/154383405-e4089e01-9fdf-40df-b32f-6d94b6161f65.png)
![image](https://user-images.githubusercontent.com/60089252/154384126-ef3b733e-aeba-4b77-8041-fbf30e158fad.png)
browsername:chrome
node.js version:13.7.0
npm:6.13.6
branch name:master

**Comment by Emma-Qiu** [comment]
[](https://user-images.githubusercontent.com/60089252/154383371-a138a595-6e0e-456e-a463-cb7f925e77b2.png)[](https://user-images.githubusercontent.com/60089252/154383405-e4089e01-9fdf-40df-b32f-6d94b6161f65.png)[](https://user-images.githubusercontent.com/60089252/154384126-ef3b733e-aeba-4b77-8041-fbf30e158fad.png)I have seted up the window.navigator.language to be "en",but the console still show the error .If I click the Join button,the network will show Provisional headers are shown.In the edumeet source code,i have changed the mediasoup version into 2.6.19 because version of 3 i can't successfully npm install,and the redis version change to 4.0.3 so that when I npm start in the server there no error in the terminal.
image
image
image
browsername:chrome
node.js version:13.7.0
npm:6.13.6
branch name:master

**Comment by Rockung** [comment]
I have the same problem. I get the following message in Firefox dev tools:

Firefox can’t establish a connection to the server at wss://localhost:8443/socket.io/?peerId=7vupbdr1&roomId=5bw9bp4m&EIO=4&transport=websocket&sid=pYAWuTe1u59wmsKKAAAI.

edumeet:ERROR:JoinDialog Error checking login status +0ms SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data

- I changed server code  in runWebSocketServer()
  ` io = require('socket.io')(mainListener, { cookie: false, cors: true });`
- I ran app by `npm run dev`
